### ISSUE TITLE
Exception in thread odoo.service.httpd:

### ISSUE THREAD

**Issue by AbirZaat** [Yenthe666/InstallScript#104]
hello , 
i installed odoo 11 in my ubuntu server and after the configuration of mail server pop and smtp , this erros was appeared 

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/odoo/odoo-server/odoo/service/server.py", line 251, in http_thread
    self.httpd = ThreadedWSGIServerReloadable(self.interface, self.port, app)
  File "/odoo/odoo-server/odoo/service/server.py", line 103, in __init__
    handler=RequestHandler)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 577, in __init__
    self.address_family), handler)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/odoo/odoo-server/odoo/service/server.py", line 113, in server_bind
    super(ThreadedWSGIServerReloadable, self).server_bind()
  File "/usr/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

**Comment by Yenthe666** [comment]
@AbirZaat this is misuse of the system. It is already running basically, that is what the message says.

**Comment by prajithpipt** [comment]
@Yenthe666  How to solve this bug

**Comment by prajithpipt** [comment]
@Yenthe666  i have the issue; how to solve this bug

**Comment by prajithpipt** [comment]
@Yenthe666 i have  the same issue; how to solve this bug

Exception in thread odoo.service.httpd:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/odoo/odoo-server/odoo/service/server.py", line 410, in http_thread
    self.httpd = ThreadedWSGIServerReloadable(self.interface, self.port, app)
  File "/odoo/odoo-server/odoo/service/server.py", line 136, in __init__
    handler=RequestHandler)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 698, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.6/socketserver.py", line 453, in __init__
    self.server_bind()
  File "/odoo/odoo-server/odoo/service/server.py", line 151, in server_bind
    super(ThreadedWSGIServerReloadable, self).server_bind()
  File "/usr/lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.6/socketserver.py", line 467, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

**Comment by Yenthe666** [comment]
You already have an Odoo instance/service running. Stop it first and then it should be possible. Very rarely it happens if you have installed the Odoo and never rebooted.
