### ISSUE TITLE
Can't Install Odoo 12 Correctly.

### ISSUE THREAD

**Issue by muhammadkamran113** [Yenthe666/InstallScript#140]
As Ref to our conversation on [Odoo Community ](https://www.odoo.com/forum/help-1/question/how-to-run-odoo-10-and-odoo-12-together-in-one-system-on-ubuntu-16-04-144962) and twitter. Here is the problem statement.

I have installed odoo 12 but it is showing errors in the log as I have posted them in a comment under your answer you suggested on twitter to run this  ----->> sudo pip install - r requirements.txt.

Its showing following errors.

> /usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
>   warnings.warn(warning, RequestsDependencyWarning)
> DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.

Whats next now.

**Comment by tonybenoy** [comment]
Odoo 12 uses python3. When you do pip install it uses pip2.
 Try doing 
`sudo pip3 install -r requirements.txt`

**Comment by muhammadkamran113** [comment]
I have done installing **requirements.**
---------------------------------------------------------------------
Traceback (most recent call last):
  File "/kamran/kamran-server/odoo/service/server.py", line 989, in load_server_wide_modules
    odoo.modules.module.load_openerp_module(m)
  File "/kamran/kamran-server/odoo/modules/module.py", line 368, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/kamran/kamran-server/odoo/modules/module.py", line 61, in load_module
    f, path, (_suffix, _mode, type_) = imp.find_module(addon_name, ad_paths)
  File "/usr/lib/python3.5/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'web_kanban'
------------------------------------------------------------------------
Traceback (most recent call last):
  File "/kamran/kamran-server/odoo/modules/registry.py", line 60, in __new__
    return cls.registries[db_name]
  File "/kamran/kamran-server/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/kamran/kamran-server/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: 'GasandOil'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/kamran/kamran-server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/kamran/kamran-server/odoo/modules/loading.py", line 424, in load_modules
    registry.setup_models(cr)
  File "/kamran/kamran-server/odoo/modules/registry.py", line 264, in setup_models
    model._setup_base()
  File "/kamran/kamran-server/odoo/models.py", line 2579, in _setup_base
    self.env['ir.model.fields']._add_manual_fields(self)
  File "/kamran/kamran-server/odoo/addons/base/models/ir_model.py", line 940, in _add_manual_fields
    field = self._instanciate(field_data)
  File "/kamran/kamran-server/odoo/addons/base/models/ir_model.py", line 931, in _instanciate
    attrs = self._instanciate_attrs(field_data)
  File "/kamran/kamran-server/addons/mail/models/ir_model.py", line 70, in _instanciate_attrs
    attrs = super(IrModelField, self)._instanciate_attrs(field_data)
  File "/kamran/kamran-server/odoo/addons/base/models/ir_model.py", line 886, in _instanciate_attrs
    'copy': bool(field_data['copied']),
KeyError: 'copied'
2019-01-30 11:48:49,669 21204 INFO GasandOil werkzeug: 127.0.0.1 - - [30/Jan/2019 11:48:49] "GET / HTTP/1.1" 500 - 11 0.008 0.244
2019-01-30 11:48:49,677 21204 ERROR GasandOil werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/kamran/kamran-server/odoo/service/server.py", line 350, in app
    return self.app(e, s)
  File "/kamran/kamran-server/odoo/service/wsgi_server.py", line 128, in application
    return application_unproxied(environ, start_response)
  File "/kamran/kamran-server/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/kamran/kamran-server/odoo/http.py", line 1318, in __call__
    return self.dispatch(environ, start_response)
  File "/kamran/kamran-server/odoo/http.py", line 1291, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/kamran/kamran-server/odoo/http.py", line 1469, in dispatch
    odoo.registry(db).check_signaling()
  File "/kamran/kamran-server/odoo/__init__.py", line 81, in registry
    return modules.registry.Registry(database_name)
  File "/kamran/kamran-server/odoo/modules/registry.py", line 62, in __new__
    return cls.new(db_name)
  File "/kamran/kamran-server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/kamran/kamran-server/odoo/modules/loading.py", line 424, in load_modules
    registry.setup_models(cr)
  File "/kamran/kamran-server/odoo/modules/registry.py", line 264, in setup_models
    model._setup_base()
  File "/kamran/kamran-server/odoo/models.py", line 2579, in _setup_base
    self.env['ir.model.fields']._add_manual_fields(self)
  File "/kamran/kamran-server/odoo/addons/base/models/ir_model.py", line 940, in _add_manual_fields
    field = self._instanciate(field_data)
  File "/kamran/kamran-server/odoo/addons/base/models/ir_model.py", line 931, in _instanciate
    attrs = self._instanciate_attrs(field_data)
  File "/kamran/kamran-server/addons/mail/models/ir_model.py", line 70, in _instanciate_attrs
    attrs = super(IrModelField, self)._instanciate_attrs(field_data)
  File "/kamran/kamran-server/odoo/addons/base/models/ir_model.py", line 886, in _instanciate_attrs
    'copy': bool(field_data['copied']),
KeyError: 'copied' - - -
------------------------------------------------------------------------------
Please help!
I don't know whats is this or how to solve it.

**Comment by muhammadkamran113** [comment]
I have done Installing Requirements
-------------------------------------------------------------------------------
```
Traceback (most recent call last):
  File "/kamran/kamran-server/odoo/service/server.py", line 989, in load_server_wide_modules
    odoo.modules.module.load_openerp_module(m)
  File "/kamran/kamran-server/odoo/modules/module.py", line 368, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/kamran/kamran-server/odoo/modules/module.py", line 61, in load_module
    f, path, (_suffix, _mode, type_) = imp.find_module(addon_name, ad_paths)
  File "/usr/lib/python3.5/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'web_kanban'
```
---------------------------------------------------------------------------------

And after refreshing the page it throws this
----------------------------------------------------------------------------------
```
Traceback (most recent call last):
  File "/kamran/kamran-server/odoo/modules/registry.py", line 60, in __new__
    return cls.registries[db_name]
  File "/kamran/kamran-server/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/kamran/kamran-server/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: 'GasandOil'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/kamran/kamran-server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/kamran/kamran-server/odoo/modules/loading.py", line 424, in load_modules
    registry.setup_models(cr)
  File "/kamran/kamran-server/odoo/modules/registry.py", line 264, in setup_models
    model._setup_base()
  File "/kamran/kamran-server/odoo/models.py", line 2579, in _setup_base
    self.env['ir.model.fields']._add_manual_fields(self)
  File "/kamran/kamran-server/odoo/addons/base/models/ir_model.py", line 940, in _add_manual_fields
    field = self._instanciate(field_data)
  File "/kamran/kamran-server/odoo/addons/base/models/ir_model.py", line 931, in _instanciate
    attrs = self._instanciate_attrs(field_data)
  File "/kamran/kamran-server/addons/mail/models/ir_model.py", line 70, in _instanciate_attrs
    attrs = super(IrModelField, self)._instanciate_attrs(field_data)
  File "/kamran/kamran-server/odoo/addons/base/models/ir_model.py", line 886, in _instanciate_attrs
    'copy': bool(field_data['copied']),
KeyError: 'copied'
2019-01-30 11:48:49,669 21204 INFO GasandOil werkzeug: 127.0.0.1 - - [30/Jan/2019 11:48:49] "GET / HTTP/1.1" 500 - 11 0.008 0.244
2019-01-30 11:48:49,677 21204 ERROR GasandOil werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/kamran/kamran-server/odoo/service/server.py", line 350, in app
    return self.app(e, s)
  File "/kamran/kamran-server/odoo/service/wsgi_server.py", line 128, in application
    return application_unproxied(environ, start_response)
  File "/kamran/kamran-server/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/kamran/kamran-server/odoo/http.py", line 1318, in __call__
    return self.dispatch(environ, start_response)
  File "/kamran/kamran-server/odoo/http.py", line 1291, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/kamran/kamran-server/odoo/http.py", line 1469, in dispatch
    odoo.registry(db).check_signaling()
  File "/kamran/kamran-server/odoo/__init__.py", line 81, in registry
    return modules.registry.Registry(database_name)
  File "/kamran/kamran-server/odoo/modules/registry.py", line 62, in __new__
    return cls.new(db_name)
  File "/kamran/kamran-server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/kamran/kamran-server/odoo/modules/loading.py", line 424, in load_modules
    registry.setup_models(cr)
  File "/kamran/kamran-server/odoo/modules/registry.py", line 264, in setup_models
    model._setup_base()
  File "/kamran/kamran-server/odoo/models.py", line 2579, in _setup_base
    self.env['ir.model.fields']._add_manual_fields(self)
  File "/kamran/kamran-server/odoo/addons/base/models/ir_model.py", line 940, in _add_manual_fields
    field = self._instanciate(field_data)
  File "/kamran/kamran-server/odoo/addons/base/models/ir_model.py", line 931, in _instanciate
    attrs = self._instanciate_attrs(field_data)
  File "/kamran/kamran-server/addons/mail/models/ir_model.py", line 70, in _instanciate_attrs
    attrs = super(IrModelField, self)._instanciate_attrs(field_data)
  File "/kamran/kamran-server/odoo/addons/base/models/ir_model.py", line 886, in _instanciate_attrs
    'copy': bool(field_data['copied']),
KeyError: 'copied' - - -

```
What to do now. I can't understand these errors.  Please help

**Comment by tonybenoy** [comment]
I think the error might be due to the config file. Are you using the same config file for 10 and 12?

**Comment by muhammadkamran113** [comment]
Well Tony I have seen the odoo.config file in odoo-dev/odoo/debian/odoo.conf for odoo 10 and kamran-server.config file in /etc/kamran-server.config. Both are different and are at different location. What now? Y the script not working for me? Plus is the script compatible with ubuntu 16.04.

**Comment by Yenthe666** [comment]
Can you paste the output of both configuration files (and mention the version above it) please? Yes it works on Ubuntu 16.04.

**Comment by muhammadkamran113** [comment]
Odoo 10

```
[options]
; This is the password that allows database operations:
; admin_passwd = admin
db_host = False
db_port = False
db_user = odoo
db_password = False
addons_path = /usr/lib/python2.7/dist-packages/odoo/addons
```

Odoo 12

```
[options] 
; This is the password that allows database operations:
admin_passwd = admin
xmlrpc_port = 9000
logfile = /var/log/kamran/kamran-server.log
addons_path=/kamran/kamran-server/addons,/kamran/custom/addons
```

**Comment by tonybenoy** [comment]
Try adding the following to your odoo 12 conf file
> server_wide_modules = web

**Comment by muhammadkamran113** [comment]
Add the line at the end and start of the odoo 12 config file and tried it but its still not working. Showing the same errors mentioned above.

**Comment by muhammadkamran113** [comment]
Add the line at the end and start of the odoo 12 config file and tried it but its still not working. Showing the same errors mentioned above.
Sorry Closed the issue by mistake.

**Comment by Yenthe666** [comment]
I don't get where that keyerror comes from though..
Neither where "ImportError: No module named 'web_kanban'" comes from, it is not a module in Odoo 12.
Are you importing custom databases, added custom modules or something?

**Comment by muhammadkamran113** [comment]
No Yenthe I didn't made any custom modules and I don't have any database on odoo 12. Plus i am not calling or adding any database reference in the server call. What now?

**Comment by muhammadkamran113** [comment]
This is something strange:

`KeyError: 'GasandOil'`

This is the name of my database in odoo 10

**Comment by Yenthe666** [comment]
Hmm looks like the two instances or finding eachother its db's in one way or another. Did you create two different system users (and postgreSQL users) for the two instances? See
https://github.com/Yenthe666/InstallScript/blob/9e82bfbd2b7b265e1e95b344d59a4e5448e80136/odoo_install.sh#L17

**Comment by muhammadkamran113** [comment]
I didn't created a new system user for odoo 12 as already I had used odoo 8 and 10 in one login in the past. Now about odoo 12 I didn't made a new user. db user I dont have an idea. I didnt change anything in the script against database.

**Comment by Yenthe666** [comment]
Then that is your issue. You cannot run two Odoo instances on one user with this script. It will confuse the databases and does not know which database belongs to which instance.
Closing as misuse of the script 😉 
Check the readme at https://github.com/Yenthe666/InstallScript#2-modify-the-parameters-as-you-wish
