### ISSUE TITLE
does not start odoo service in ubuntu 18.04

### ISSUE THREAD

**Issue by ghost** [Yenthe666/InstallScript#201]
In versions higher than ubuntu 16.04, the script does not work for me, the odoo service does not start.

**Comment by Yenthe666** [comment]
Anything in the logs? What happens if you manually start it with `./odoo-bin -c /etc/odoo/your-server.conf`?

**Comment by ghost** [comment]
Hi, thanks for answering, I did what you told me and I could see that the problem is that the service does not start because a set of python dependencies were missing that apparently the script is not installing and as the odoo service did not start the 1st time, never I wrote the errors in the log /var/log/odoo/odoo-server.log

**Comment by Yenthe666** [comment]
Hmm interesting. Can you please post the output of the log that mentions the issues with the requirements? It installs the official requirements from Odoo (https://github.com/odoo/odoo/blob/13.0/requirements.txt) so this is odd.

**Comment by ghost** [comment]
The problem occurs while installing odoo12 on ubuntu server 18.04.03. The dependencies that prevent me from starting the service, are dependencies included in the requirements file, to solve the situation I reinstalled those dependencies using pip3. 
These are the missing dependencies:
Werkzeug
PyPDF2
psycopg2
psutil
html2text

**Comment by Yenthe666** [comment]
That's odd because they are in the requirements file too. For example PyPDF2 1.26.0 is in the requirements.txt file. You say "to solve the situation I reinstalled those dependencies using pip3". Does that mean they where installed but did not work or?

**Comment by ghost** [comment]
Exactly, it means that.

**Comment by fgarcia-humanoide** [comment]
It failed for me allso.

ubuntu 18.04
odoo 12
nginx yes

odoo did not work and i solved it with

wget  ----- requirements.txt
pip3 install -r requirements.txt

now I can reach odoo in port 8069 but not in https

nginx is donw

root@nginx-odoo12-01:~# systemctl status nginx.service
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2020-02-02 09:17:01 UTC; 48s ago
     Docs: man:nginx(8)
  Process: 1246 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)

Feb 02 09:17:01 nginx-odoo12-01 systemd[1]: Starting A high performance web server and a reverse proxy server...
Feb 02 09:17:01 nginx-odoo12-01 nginx[1246]: nginx: [emerg] invalid number of arguments in "proxy_set_header" directive in /etc/nginx/sites-enabled/odoo:14
Feb 02 09:17:01 nginx-odoo12-01 nginx[1246]: nginx: configuration file /etc/nginx/nginx.conf test failed
Feb 02 09:17:01 nginx-odoo12-01 systemd[1]: nginx.service: Control process exited, code=exited status=1
Feb 02 09:17:01 nginx-odoo12-01 systemd[1]: nginx.service: Failed with result 'exit-code'.
Feb 02 09:17:01 nginx-odoo12-01 systemd[1]: Failed to start A high performance web server and a reverse proxy server.

**Comment by Yenthe666** [comment]
Interesting, I'll check it soon. Remember me in four days if you haven't heard back from me

**Comment by fgarcia-humanoide** [comment]
Thanks

Error log nginx

2020/02/02 08:56:22 [emerg] 20853#20853: invalid number of arguments in "proxy_set_header" directive in /etc/nginx/sites-enabled/odoo:14
2020/02/02 09:00:01 [alert] 20750#20750: *19 open socket #11 left in connection 3
2020/02/02 09:00:01 [alert] 20750#20750: *20 open socket #12 left in connection 4
2020/02/02 09:00:01 [alert] 20750#20750: *18 open socket #3 left in connection 5
2020/02/02 09:00:01 [alert] 20750#20750: *21 open socket #13 left in connection 6
2020/02/02 09:00:01 [alert] 20750#20750: aborting
2020/02/02 09:00:16 [emerg] 811#811: invalid number of arguments in "proxy_set_header" directive in /etc/nginx/sites-enabled/odoo:14
2020/02/02 09:08:20 [emerg] 813#813: invalid number of arguments in "proxy_set_header" directive in /etc/nginx/sites-enabled/odoo:14
2020/02/02 09:15:41 [emerg] 812#812: invalid number of arguments in "proxy_set_header" directive in /etc/nginx/sites-enabled/odoo:14
2020/02/02 09:17:01 [emerg] 1246#1246: invalid number of arguments in "proxy_set_header" directive in /etc/nginx/sites-enabled/odoo:14

**Comment by gabrielmoralessaez** [comment]
I have a similar problem, when i try install odoo 11 on digital ocean with your script, and i try to run the server, odoo not run.

**Comment by Yenthe666** [comment]
@leyetfz & @fgarcia-humanoide I think this commit (https://github.com/Yenthe666/InstallScript/commit/e5e7fba5b392e194c2a61758810646e467da8110) fixes your issue.
@gabrielmoralessaez please check the log and post the output of the errors

**Comment by rexefe** [comment]
@Yenthe666 
the service is started, but i get this error when i check the localhost link via curl 
curl: (52) Empty reply from server

**Comment by rexefe** [comment]
rexefe@ThinkMagine:~$ sudo tail -f /var/log/odoo/odoo-server.log 
2020-02-29 01:09:36,886 10230 INFO ? odoo: database: default@default:default 
2020-02-29 01:09:36,973 10230 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
2020-02-29 01:09:41,738 10230 INFO ? odoo.service.server: Initiating shutdown 
2020-02-29 01:09:41,739 10230 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2020-02-29 01:10:10,114 10255 INFO ? odoo: Odoo version 12.0 
2020-02-29 01:10:10,114 10255 INFO ? odoo: Using configuration file at /etc/odoo-server.conf 
2020-02-29 01:10:10,115 10255 INFO ? odoo: addons paths: ['/odoo/odoo-server/addons', '/odoo/custom/addons', '/odoo/odoo-server/odoo/addons'] 
2020-02-29 01:10:10,115 10255 INFO ? odoo: database: default@default:default 
2020-02-29 01:10:10,200 10255 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
2020-02-29 01:10:10,292 10255 INFO ? odoo.service.server: HTTP service (werkzeug) running on ThinkMagine:8069 
^C
rexefe@ThinkMagine:~$ sudo nano /etc/odoo-server.conf
rexefe@ThinkMagine:~$ ^C
rexefe@ThinkMagine:~$ curl localhost:8069
curl: (52) Empty reply from server

**Comment by rexefe** [comment]
rexefe@ThinkMagine:~$ sudo tail -f /var/log/odoo/odoo-server.log 
2020-02-29 01:09:36,886 10230 INFO ? odoo: database: default@default:default 
2020-02-29 01:09:36,973 10230 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
2020-02-29 01:09:41,738 10230 INFO ? odoo.service.server: Initiating shutdown 
2020-02-29 01:09:41,739 10230 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2020-02-29 01:10:10,114 10255 INFO ? odoo: Odoo version 12.0 
2020-02-29 01:10:10,114 10255 INFO ? odoo: Using configuration file at /etc/odoo-server.conf 
2020-02-29 01:10:10,115 10255 INFO ? odoo: addons paths: ['/odoo/odoo-server/addons', '/odoo/custom/addons', '/odoo/odoo-server/odoo/addons'] 
2020-02-29 01:10:10,115 10255 INFO ? odoo: database: default@default:default 
2020-02-29 01:10:10,200 10255 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
2020-02-29 01:10:10,292 10255 INFO ? odoo.service.server: HTTP service (werkzeug) running on ThinkMagine:8069 
rexefe@ThinkMagine:~$ curl localhost:8069
curl: (52) Empty reply from server

**Comment by rexefe** [comment]
rexefe@ThinkMagine:/odoo/odoo-server$ sudo ./start.sh 
Exception in thread odoo.service.httpd:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/odoo/odoo-server/odoo/service/server.py", line 435, in http_thread
    self.httpd = ThreadedWSGIServerReloadable(self.interface, self.port, app)
  File "/odoo/odoo-server/odoo/service/server.py", line 149, in __init__
    handler=RequestHandler)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 476, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/lib/python3.6/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/odoo/odoo-server/odoo/service/server.py", line 164, in server_bind
    super(ThreadedWSGIServerReloadable, self).server_bind()
  File "/usr/lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.6/socketserver.py", line 470, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

**Comment by abhisheiks** [comment]
Hi,
Thank you for the script, I have successfully install odoo 13 on ubuntu 18.04 using your install script. However I would like to install and use odoo 8 on ubuntu 18.04 and when I use your script, the installation is successful and after reboot (odoo-server and postgres) are running however we cannot access URL: lcoalhost:8069. To check if port 8069 was listing I used command 
sudo netstat -tulpn | grep LISTEN
and found 8069 was not showing in the list.

Can you please advice on this.

FYI please see the output of your scrip once the installation is complete 
-----------------------------------------------------------
Done! The Odoo server is up and running. Specifications:
Port: 8069
User service: odoo
User PostgreSQL: odoo
Code location: odoo
Addons folder: odoo/odoo-server/addons/
Password superadmin (database): -hidden-
Start Odoo service: sudo service odoo-server start
Stop Odoo service: sudo service odoo-server stop
Restart Odoo service: sudo service odoo-server restart
-----------------------------------------------------------


Thank in advance.
Abhi

**Comment by Yenthe666** [comment]
@abhisheiks the process is pretty much always the same:
1) Check the logs
2) If no logs start the Odoo manually from the command line and check the logs

**Comment by rexefe** [comment]
2020-03-07 07:49:40,105 3086 INFO ? odoo: Odoo version 12.0 
2020-03-07 07:49:40,106 3086 INFO ? odoo: addons paths: ['/home/rexefe/.local/share/Odoo/addons/12.0', '/odoo/odoo-server/odoo/addons', '/odoo/odoo-server/addons'] 
2020-03-07 07:49:40,107 3086 INFO ? odoo: database: default@default:default 
2020-03-07 07:49:40,498 3086 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
Exception in thread odoo.service.httpd:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/odoo/odoo-server/odoo/service/server.py", line 435, in http_thread
    self.httpd = ThreadedWSGIServerReloadable(self.interface, self.port, app)
  File "/odoo/odoo-server/odoo/service/server.py", line 149, in __init__
    handler=RequestHandler)
  File "/home/rexefe/.local/lib/python3.6/site-packages/werkzeug/serving.py", line 476, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/lib/python3.6/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/odoo/odoo-server/odoo/service/server.py", line 164, in server_bind
    super(ThreadedWSGIServerReloadable, self).server_bind()
  File "/usr/lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.6/socketserver.py", line 470, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

**Comment by rexefe** [comment]
@Yenthe666 , Im making progress, its says 

2020-03-07 07:54:34,456 3607 INFO ? odoo: Odoo version 12.0 
2020-03-07 07:54:34,457 3607 INFO ? odoo: addons paths: ['/home/rexefe/.local/share/Odoo/addons/12.0', '/odoo/odoo-server/odoo/addons', '/odoo/odoo-server/addons'] 
2020-03-07 07:54:34,457 3607 INFO ? odoo: database: default@default:default 
2020-03-07 07:54:34,546 3607 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
2020-03-07 07:54:34,644 3607 INFO ? odoo.service.server: HTTP service (werkzeug) running on ThinkMagine:8069 
2020-03-07 07:55:19,812 3607 INFO ? odoo.http: HTTP Configuring static files 
2020-03-07 07:55:19,821 3607 INFO ? odoo.sql_db: Connection to the database failed 
2020-03-07 07:55:19,824 3607 INFO ? werkzeug: 127.0.0.1 - - [07/Mar/2020 07:55:19] "GET / HTTP/1.1" 500 - 0 0.000 0.008
2020-03-07 07:55:19,939 3607 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/home/rexefe/.local/lib/python3.6/site-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/home/rexefe/.local/lib/python3.6/site-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/odoo/odoo-server/odoo/service/server.py", line 434, in app
    return self.app(e, s)
  File "/odoo/odoo-server/odoo/service/wsgi_server.py", line 142, in application
    return application_unproxied(environ, start_response)
  File "/odoo/odoo-server/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/odoo/odoo-server/odoo/http.py", line 1320, in __call__
    return self.dispatch(environ, start_response)
  File "/odoo/odoo-server/odoo/http.py", line 1293, in __call__
    return self.app(environ, start_wrapped)
  File "/home/rexefe/.local/lib/python3.6/site-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/odoo/odoo-server/odoo/http.py", line 1453, in dispatch
    self.setup_db(httprequest)
  File "/odoo/odoo-server/odoo/http.py", line 1376, in setup_db
    httprequest.session.db = db_monodb(httprequest)
  File "/odoo/odoo-server/odoo/http.py", line 1537, in db_monodb
    dbs = db_list(True, httprequest)
  File "/odoo/odoo-server/odoo/http.py", line 1504, in db_list
    dbs = odoo.service.db.list_dbs(force)
  File "/odoo/odoo-server/odoo/service/db.py", line 375, in list_dbs
    with closing(db.cursor()) as cr:
  File "/odoo/odoo-server/odoo/sql_db.py", line 657, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/odoo/odoo-server/odoo/sql_db.py", line 171, in __init__
    self._cnx = pool.borrow(dsn)
  File "/odoo/odoo-server/odoo/sql_db.py", line 540, in _locked
    return fun(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/sql_db.py", line 608, in borrow
    **connection_info)
  File "/usr/local/lib/python3.6/dist-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  role "root" does not exist - - -
2020-03-07 07:55:19,982 3607 INFO ? odoo.sql_db: Connection to the database failed 
2020-03-07 07:55:19,984 3607 INFO ? werkzeug: 127.0.0.1 - - [07/Mar/2020 07:55:19] "GET /favicon.ico HTTP/1.1" 500 - 0 0.000 0.006
2020-03-07 07:55:19,990 3607 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/home/rexefe/.local/lib/python3.6/site-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/home/rexefe/.local/lib/python3.6/site-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/odoo/odoo-server/odoo/service/server.py", line 434, in app
    return self.app(e, s)
  File "/odoo/odoo-server/odoo/service/wsgi_server.py", line 142, in application
    return application_unproxied(environ, start_response)
  File "/odoo/odoo-server/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/odoo/odoo-server/odoo/http.py", line 1320, in __call__
    return self.dispatch(environ, start_response)
  File "/odoo/odoo-server/odoo/http.py", line 1293, in __call__
    return self.app(environ, start_wrapped)
  File "/home/rexefe/.local/lib/python3.6/site-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/odoo/odoo-server/odoo/http.py", line 1453, in dispatch
    self.setup_db(httprequest)
  File "/odoo/odoo-server/odoo/http.py", line 1376, in setup_db
    httprequest.session.db = db_monodb(httprequest)
  File "/odoo/odoo-server/odoo/http.py", line 1537, in db_monodb
    dbs = db_list(True, httprequest)
  File "/odoo/odoo-server/odoo/http.py", line 1504, in db_list
    dbs = odoo.service.db.list_dbs(force)
  File "/odoo/odoo-server/odoo/service/db.py", line 375, in list_dbs
    with closing(db.cursor()) as cr:
  File "/odoo/odoo-server/odoo/sql_db.py", line 657, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/odoo/odoo-server/odoo/sql_db.py", line 171, in __init__
    self._cnx = pool.borrow(dsn)
  File "/odoo/odoo-server/odoo/sql_db.py", line 540, in _locked
    return fun(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/sql_db.py", line 608, in borrow
    **connection_info)
  File "/usr/local/lib/python3.6/dist-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  role "root" does not exist - - -

**Comment by rexefe** [comment]
i created user root

it works now, 

but

odoo only runs when i run start it manually

**Comment by Yenthe666** [comment]
Yeah you must've done something wrong and this is risky. Don't run the database with the root user, it should be owned by a separate user which has less system rights honestly.
Instead change the owner for postgreSQL

**Comment by rexefe** [comment]
understandable, how do i chaneg this, please any instructions will do

**Comment by Yenthe666** [comment]
See https://stackoverflow.com/questions/4313323/how-to-change-owner-of-postgresql-database

**Comment by rexefe** [comment]
okay, i'll review it, thank you

**Comment by ghost** [comment]
Hello, after reviewing the script in detail, as well as the error (I was the one who started the issue), the problem is that the script does not get to run completely.
By installing this lxml dependency, the script is interrupted, hence the errors later.
I solved the problem, amplifying the performance of the VPS, by giving it more RAM, everything was stirred and the installation works correctly.
I didn't have to modify anything in the script.

**Comment by Yenthe666** [comment]
Hmm so this comes back to what more people reported: if there is not enough RAM and something doesn't finish successfully it screws the installation process or the service. Thanks for the clarification!
