### ISSUE TITLE
odoo 11 problem with werkzeug.contrib

### ISSUE THREAD

**Issue by gabrielmoralessaez** [Yenthe666/InstallScript#204]
I tried to install odoo 11 in digitalocean with your stript, but I couldn't start the server because when entering the odoo-bin, the following error occur

`Traceback (most recent call last):
  File "./odoo-bin", line 5, in <module>
    import odoo
  File "/odoo/odoo-server/odoo/__init__.py", line 88, in <module>
    from . import service
  File "/odoo/odoo-server/odoo/service/__init__.py", line 7, in <module>
    from . import wsgi_server
  File "/odoo/odoo-server/odoo/service/wsgi_server.py", line 25, in <module>
    import werkzeug.contrib.fixers
ModuleNotFoundError: No module named 'werkzeug.contrib'
`

i have installed odoo 12 and 13 with your script and i never had that error.

I'm waiting for your answer. Thank you.

**Comment by gabrielmoralessaez** [comment]
I'll close this question, and leave the answer in case it serves anyone
greetings :)
`pip3 install Werkzeug==0.11.15`
