### ISSUE TITLE
Error after installing enterprise Odoo 14 script

### ISSUE THREAD

**Issue by chancald** [Yenthe666/InstallScript#266]
After installing enterprise I get this error (with a fresh database too):

Traceback:
Error: Template HomeMenuWrapper does not exist
    at QWeb.render (http://23.96.118.242/web/content/205-bbf6f83/web.assets_common.js:949:92)
    at HomeMenuWrapper.__render (http://23.96.118.242/web/content/205-bbf6f83/web.assets_common.js:1269:33)
    at HomeMenuWrapper.__prepareAndRender (http://23.96.118.242/web/content/205-bbf6f83/web.assets_common.js:1267:29)

I used the Odoo 14 script and selected to install Enterprise and Nginx in a Azure VM instance (3GB of RAM) with Ubuntu 18.04.

**Comment by Yenthe666** [comment]
Well, that looks like an issue in Odoo itself honestly :) Your Odoo is loading and that's what the script should do.
Any errors in the logs or through the installation?
