### ISSUE TITLE
Scripts ends at nginx: [error] invalid PID number "" in "/run/nginx.pid"

### ISSUE THREAD

**Issue by ishmumx** [Yenthe666/InstallScript#278]
The script installs, then goes:

Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator nginx, Installer nginx
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for odoo.mywebsitenameremoved.com
nginx: [error] invalid PID number "" in "/run/nginx.pid"
Cleaning up challenges
nginx: [error] invalid PID number "" in "/run/nginx.pid"
Encountered exception during recovery:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 75, in handle_authorizations
    resp = self._solve_challenges(aauthzrs)
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 139, in _solve_challenges
    resp = self.auth.perform(all_achalls)
  File "/usr/lib/python3/dist-packages/certbot_nginx/configurator.py", line 1071, in perform
    self.restart()
  File "/usr/lib/python3/dist-packages/certbot_nginx/configurator.py", line 881, in restart
    nginx_restart(self.conf('ctl'), self.nginx_conf)
  File "/usr/lib/python3/dist-packages/certbot_nginx/configurator.py", line 1141, in nginx_restart
    "nginx restart failed:\n%s\n%s" % (out.read(), err.read()))
certbot.errors.MisconfigurationError: nginx restart failed:
b''
b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/error_handler.py", line 108, in _call_registered
    self.funcs[-1]()
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 323, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/usr/lib/python3/dist-packages/certbot_nginx/configurator.py", line 1090, in cleanup
    self.restart()
  File "/usr/lib/python3/dist-packages/certbot_nginx/configurator.py", line 881, in restart
    nginx_restart(self.conf('ctl'), self.nginx_conf)
  File "/usr/lib/python3/dist-packages/certbot_nginx/configurator.py", line 1141, in nginx_restart
    "nginx restart failed:\n%s\n%s" % (out.read(), err.read()))
certbot.errors.MisconfigurationError: nginx restart failed:
b''
b''
nginx restart failed:
b''
b''

Ubuntu 18.04 Fresh Install. 
Server has 8 cores and 5500MB of RAM dedicated to the VM. The IP is pointed at the domain and nslookup returns the public IP. What to do? Thank you sir.

**Comment by Yenthe666** [comment]
Not really sure. `certbot.errors.MisconfigurationError: nginx restart failed:` seems to be the issue. Can you check your Nginx configs and logs?

**Comment by ishmumx** [comment]
> Not really sure. `certbot.errors.MisconfigurationError: nginx restart failed:` seems to be the issue. Can you check your Nginx configs and logs?

Apologies for not getting back to this issue. Yes, I did figure it out. I assigned the VM 2 cores and 2GB of RAM and it breezed through. There is a bug in Odoo that I found, but that is the Odoo team's problem of course :) 

This issue is reproducible using 1 core and 1GB of RAM

Thank you boss!!

**Comment by Yenthe666** [comment]
Yeah 1 core & 1GB of RAM is never adviced. It's even written in the main text on the homepage (See https://github.com/yenthe666/installScript#minimal-server-requirements).
