### ISSUE TITLE
[v14] missing dependency for Enterprise: pdfminer

### ISSUE THREAD

**Issue by ray-odoo** [Yenthe666/InstallScript#293]
![image](https://user-images.githubusercontent.com/41073831/104525837-ed15c300-55b5-11eb-8424-e4b78d7b4bbe.png)

To meet the dependency:

pip3 install pdfminer.six

**Comment by Yenthe666** [comment]
Yep indeed, I noticed this one last week too, just didn't add it yet.
Added in at https://github.com/Yenthe666/InstallScript/commit/897e7d49accd1c7fd6b31694ea45ebe3bb999b94 - thanks for reporting!

**Comment by rousseldenis** [comment]
@Yenthe666 This should be added in setup.py

**Comment by XeJames** [comment]
Hey guys,  after a fresh install of 16 I restored my updated db.  Warning about pdfminer.six - so I guess @Yenthe666  suggestion about adding it hasn't been implemented yet(?).

I installed pdfminer.six: ```sudo pip3 install pdfminer.six```

Odoo won't boot now.   Rolled back snapshot and installed pdfminer.six BEFORE db restore - still won't load so problem was not the db restore.

Error is crypto and cannot load base or web:

`2023-01-25 13:54:50,116 427 CRITICAL ? odoo.modules.module: Couldn't load module web
2023-01-25 13:54:50,116 427 CRITICAL ? odoo.modules.module: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
2023-01-25 13:54:50,116 427 ERROR ? odoo.service.server: Failed to load server-wide module `web`.
The `web` module is provided by the addons found in the `openerp-web` project.
Maybe you forgot to add those addons in your addons_path configuration.
Traceback (most recent call last):
  File "/odoo/odoo/service/server.py", line 1239, in load_server_wide_modules
    odoo.modules.module.load_openerp_module(m)
  File "/odoo/odoo/modules/module.py", line 432, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/odoo/addons/web/__init__.py", line 4, in <module>
    from . import controllers
  File "/odoo/addons/web/controllers/__init__.py", line 5, in <module>
    from . import database
  File "/odoo/addons/web/controllers/database.py", line 24, in <module>
    from odoo.addons.base.models.ir_qweb import render as qweb_render
  File "/odoo/odoo/addons/base/__init__.py", line 5, in <module>
    from . import models
  File "/odoo/odoo/addons/base/models/__init__.py", line 21, in <module>
    from . import ir_mail_server
  File "/odoo/odoo/addons/base/models/ir_mail_server.py", line 19, in <module>
    from OpenSSL import crypto as SSLCrypto
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1556, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1577, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'`

**SOLUTION:**  In _**early testing,**_ the problem appears to be a bad new crypto version (39.0.0).  Downgrading to 36.0.2 seems to solve the problem.

```
sudo pip3 uninstall cryptography
sudo pip3 install --upgrade cryptography==36.0.2
```

I'm looking for any advice on why this may - or may not - be the right solution before I apply to client servers.

**Comment by Yenthe666** [comment]
See also https://stackoverflow.com/questions/73830524/attributeerror-module-lib-has-no-attribute-x509-v-flag-cb-issuer-check and https://github.com/odoo/odoo/issues/99809

**Comment by XeJames** [comment]
FWIW:  Odoo devs consulted and confirmed that pinning crypto to 36.0.2 is the accepted solution internally as well.  I'm going to call this the official solution.

Thanks @Yenthe666

**Comment by colinstu12** [comment]
If this helps anyone else: running into a similar snag, urllib3 needed to be at 2.0.5, it was on 1.26.5 before and nothing seemed to be pointing this out.
