### ISSUE TITLE
Issue sending email quote?

### ISSUE THREAD

**Issue by killmasta93** [Yenthe666/InstallScript#322]
Hi 
Currently trying to create a quote and send though email by Odoo but im getting this error

```
2021-10-08 16:45:03,821 125317 INFO odoo odoo.addons.mail.models.mail_render_mixin: Failed to load template "${object.company_id.name} ${object.state in ('draft', 'sent') and (ctx.get('proforma') and 'Proforma' or ‘Presupuesto’) or ‘Pedido’} (Ref ${object.name or 'n/a' })" 
Traceback (most recent call last):
  File "/odoo/odoo-server/addons/mail/models/mail_render_mixin.py", line 333, in _render_template_jinja
    template = jinja_env.from_string(tools.ustr(template_txt))
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 941, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.8/dist-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
```

i went to settings of sales  and made sure everything was correct 

![image](https://user-images.githubusercontent.com/13953629/136594270-aab3ee56-c062-437c-bb91-a8b23aed4fce.png)

**Comment by Yenthe666** [comment]
This is a translation issue in your language. Has to be correct on www.transifex.com/odoo and it's not related to our scripts.
