### ISSUE TITLE
Ubuntu 18.0.4.6 LTS and Odoo 15.0 CE - unusable Python version installed (3.6.9)

### ISSUE THREAD

**Issue by Rad0van** [Yenthe666/InstallScript#333]
The script itself works fine but the Python version being installed is Python 3.6.9. Attempt to start Odoo fails with:
```
root@myserver:/odoo/odoo-server# ./start.sh 
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo-bin", line 5, in <module>
    import odoo
  File "/odoo/odoo-server/odoo/__init__.py", line 19, in <module>
    assert sys.version_info > (3, 7), "Outdated python version detected, Odoo requires Python >= 3.7 to run."
AssertionError: Outdated python version detected, Odoo requires Python >= 3.7 to run.

```
I guess I can fix this manually but for less skilled user this could ba taken care of. Not sure what the best approach would be though. Depending on Odoo version select the appropriate Python version?

**Comment by bilaluddin2k** [comment]
@Rad0van i am  facing the same issue, plz can you tell me how to fix that...kindly help.
i have 3 odoo13 running on same machine and have installed odoo15, but when I start the service it gives this error python version, then I downloaded python3.8 and set it to default but it still gives the same error...plz help me
