### ISSUE TITLE
"AssertionError: Outdated python version detected, Odoo requires Python >= 3.7 to run" please help!

### ISSUE THREAD

**Issue by bilaluddin2k** [Yenthe666/InstallScript#344]
i tried to install python 3.8 and set it to default but still I get the same issue.
should I restart the server?
Traceback (most recent call last):
  File "./odoo-bin", line 5, in <module>
    import odoo
  File "/rxg15/rxg15-server/odoo/__init__.py", line 19, in <module>
    assert sys.version_info > (3, 7), "Outdated python version detected, Odoo requires Python >= 3.7 to run."
AssertionError: Outdated python version detected, Odoo requires Python >= 3.7 to run.

**Comment by bryanmysp** [comment]
you can fix it?
