### ISSUE TITLE
[Not Found] when trying to visit URL only when installing enterprise

### ISSUE THREAD

**Issue by Moonif** [Yenthe666/InstallScript#394]
Hello,

Thank you very much for this awesome script.

Unfortunately, I'm facing an issue:
Installing Odoo with default settings, works perfectly fine, but when setting Is_Enterprise to True, everything is installed correctly, all enterprise addons are present (I'm an Odoo partner), but the thing is visiting the (Digitalocean droplet) IP address, I get a "Not Found" web page.
As mentioned earlier, I'm using DigitalOcean, I tried with multiple settings, deleted projects, droplets, but always the same result.

Can you please help?

**Comment by Moonif** [comment]
Log:

2023-05-24 18:38:04,119 48892 INFO ? odoo: Odoo version 16.0
2023-05-24 18:38:04,119 48892 INFO ? odoo: Using configuration file at /etc/odoo-server.conf
2023-05-24 18:38:04,119 48892 INFO ? odoo: addons paths: ['/odoo/odoo-server/odoo/addons', '/odoo/.local/share/O>
2023-05-24 18:38:04,120 48892 INFO ? odoo: database: default@default:default
2023-05-24 18:38:04,301 48892 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary >
2023-05-24 18:38:04,403 48892 CRITICAL ? odoo.modules.module: Couldn't load module base
2023-05-24 18:38:04,403 48892 CRITICAL ? odoo.modules.module: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSU>
2023-05-24 18:38:04,403 48892 ERROR ? odoo.service.server: Failed to load server-wide module `base`.
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/service/server.py", line 1248, in load_server_wide_modules
    odoo.modules.module.load_openerp_module(m)
  File "/odoo/odoo-server/odoo/modules/module.py", line 432, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/odoo/odoo-server/odoo/addons/base/__init__.py", line 5, in <module>
    from . import models
  File "/odoo/odoo-server/odoo/addons/base/models/__init__.py", line 21, in <module>
    from . import ir_mail_server
  File "/odoo/odoo-server/odoo/addons/base/models/ir_mail_server.py", line 19, in <module>
    from OpenSSL import crypto as SSLCrypto
  File "/usr/local/lib/python3.8/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/local/lib/python3.8/dist-packages/OpenSSL/crypto.py", line 1556, in <module>
    class X509StoreFlags(object):
  File "/usr/local/lib/python3.8/dist-packages/OpenSSL/crypto.py", line 1577, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
2023-05-24 18:38:04,419 48892 CRITICAL ? odoo.modules.module: Couldn't load module web
2023-05-24 18:38:04,419 48892 CRITICAL ? odoo.modules.module: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSU>
2023-05-24 18:38:04,419 48892 ERROR ? odoo.service.server: Failed to load server-wide module `web`.
The `web` module is provided by the addons found in the `openerp-web` project.
Maybe you forgot to add those addons in your addons_path configuration.
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/service/server.py", line 1248, in load_server_wide_modules
    odoo.modules.module.load_openerp_module(m)
  File "/odoo/odoo-server/odoo/modules/module.py", line 432, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/odoo/odoo-server/addons/web/__init__.py", line 4, in <module>
    from . import controllers
  File "/odoo/odoo-server/addons/web/controllers/__init__.py", line 5, in <module>
    from . import database
  File "/odoo/odoo-server/addons/web/controllers/database.py", line 19, in <module>
    from odoo.addons.base.models.ir_qweb import render as qweb_render
  File "/odoo/odoo-server/odoo/addons/base/__init__.py", line 5, in <module>
    from . import models
  File "/odoo/odoo-server/odoo/addons/base/models/__init__.py", line 21, in <module>
    from . import ir_mail_server
  File "/odoo/odoo-server/odoo/addons/base/models/ir_mail_server.py", line 19, in <module>
    from OpenSSL import crypto as SSLCrypto
  File "/usr/local/lib/python3.8/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/local/lib/python3.8/dist-packages/OpenSSL/crypto.py", line 1556, in <module>
    class X509StoreFlags(object):
  File "/usr/local/lib/python3.8/dist-packages/OpenSSL/crypto.py", line 1577, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
2023-05-24 18:38:04,423 48892 INFO ? odoo.service.server: HTTP service (werkzeug) running on alhayah:8069 
2023-05-24 18:38:49,343 48892 INFO ? werkzeug: 5.37.121.53 - - [24/May/2023 18:38:49] "GET / HTTP/1.0" 404 - 1 0>
2023-05-24 18:38:49,610 48892 INFO ? werkzeug: 5.37.121.53 - - [24/May/2023 18:38:49] "GET /favicon.ico HTTP/1.0>
2023-05-24 18:38:56,131 48892 INFO ? werkzeug: 5.37.121.53 - - [24/May/2023 18:38:56] "GET / HTTP/1.1" 404 - 1 0>
2023-05-24 18:38:56,366 48892 INFO ? werkzeug: 5.37.121.53 - - [24/May/2023 18:38:56] "GET /favicon.ico HTTP/1.1>

**Comment by noblesocius** [comment]
#393 
Looks like the same issue.
