### ISSUE TITLE
17.0 on Ubuntu 22.04

### ISSUE THREAD

**Issue by cliffkujala** [Yenthe666/InstallScript#405]
Has anyone tested the script on 17.0 yet?  I ran through it a few times this weekend on fresh Ubuntu 22.04 servers and received some errors, plus had to do some extra steps to get some other dependencies installed after the script ran.  I'm not a pro at this by any means, but these are the things I did in order to not receive so many errors and to get Odoo to actually start and run.

Lines commented out to avoid unsigned repository warnings:
Line 70
Line 72

Found a dependency listed on https://www.odoo.com/documentation/17.0/administration/install/source.html that was not on line 101 of the script:
Added `libpq-dev` to line 101

After the script ran, I had 500 Page Not Found errors when trying to load http://ipaddress:8069 and the following errors in the Odoo Log
```
2023-11-27 04:16:50,113 42406 INFO ? odoo: Odoo version 17.0
2023-11-27 04:16:50,113 42406 INFO ? odoo: Using configuration file at /etc/odoo-server.conf
2023-11-27 04:16:50,113 42406 INFO ? odoo: addons paths: ['/odoo/odoo-server/odoo/addons', '/odoo/.local/share/Odoo/addons/17.0', '/odoo/enterprise/addons', '/odoo/odoo-server/addons']
2023-11-27 04:16:50,113 42406 INFO ? odoo: database: default@default:default
2023-11-27 04:16:50,267 42406 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /bin/wkhtmltopdf
2023-11-27 04:16:50,352 42406 CRITICAL ? odoo.modules.module: Couldn't load module web
2023-11-27 04:16:50,353 42406 ERROR ? odoo.service.server: Failed to load server-wide module `web`.
The `web` module is provided by the addons found in the `openerp-web` project.
Maybe you forgot to add those addons in your addons_path configuration.
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/service/server.py", line 1251, in load_server_wide_modules
    odoo.modules.module.load_openerp_module(m)
  File "/odoo/odoo-server/odoo/modules/module.py", line 390, in load_openerp_module
    __import__(qualname)
  File "/odoo/odoo-server/addons/web/__init__.py", line 4, in <module>
    from . import controllers
  File "/odoo/odoo-server/addons/web/controllers/__init__.py", line 4, in <module>
    from . import binary
  File "/odoo/odoo-server/addons/web/controllers/binary.py", line 19, in <module>
    from odoo.addons.base.models.assetsbundle import ANY_UNIQUE
  File "/odoo/odoo-server/odoo/addons/base/__init__.py", line 5, in <module>
    from . import models
  File "/odoo/odoo-server/odoo/addons/base/models/__init__.py", line 21, in <module>
    from . import ir_mail_server
  File "/odoo/odoo-server/odoo/addons/base/models/ir_mail_server.py", line 19, in <module>
    from OpenSSL import crypto as SSLCrypto
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 3279, in <module>
    _lib.OpenSSL_add_all_algorithms()
AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
2023-11-27 04:16:50,358 42406 CRITICAL ? odoo.modules.module: Couldn't load module base
2023-11-27 04:16:50,358 42406 ERROR ? odoo.service.server: Failed to load server-wide module `base`.
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/service/server.py", line 1251, in load_server_wide_modules
    odoo.modules.module.load_openerp_module(m)
  File "/odoo/odoo-server/odoo/modules/module.py", line 390, in load_openerp_module
    __import__(qualname)
  File "/odoo/odoo-server/odoo/addons/base/__init__.py", line 5, in <module>
    from . import models
  File "/odoo/odoo-server/odoo/addons/base/models/__init__.py", line 21, in <module>
    from . import ir_mail_server
  File "/odoo/odoo-server/odoo/addons/base/models/ir_mail_server.py", line 19, in <module>
    from OpenSSL import crypto as SSLCrypto
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 3279, in <module>
    _lib.OpenSSL_add_all_algorithms()
AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
```

I ran the following two commands (which are on the [Odoo Source Install Documentation Page for v17](https://www.odoo.com/documentation/17.0/administration/install/source.html#dependencies)) and then restarted the server and Odoo loaded without errors in the log.
```
 cd /path/to/odoo/community/git
 sed -n -e '/^Depends:/,/^Pre/ s/ python3-\(.*\),/python3-\1/p' debian/control | sudo xargs apt-get install -y
```
```
 cd /path/to/odoo/community/git
 pip install -r requirements.txt
```

**Comment by cliffkujala** [comment]
Turns out adding `libpq-dev` to line 101 is redundant since it is already on Line 75.

**Comment by Royedc4** [comment]
Confirmed ✅

**Comment by cliffkujala** [comment]
@Yenthe666 any thoughts on the above?  Have you had a chance to test the script on Ubuntu 22.04 with V17?

**Comment by Yenthe666** [comment]
Hey! I'm sorry but I haven't had time yet :-( My team/company is short on time and we in general run instances on odoo.sh now.
It would be great to get some PR's here.

**Comment by cliffkujala** [comment]
> we in general run instances on odoo.sh now.

Separate topic, but I'd love to discuss with you some issues I have on Odoo.SH and see if you have any solutions which Official Odoo could not solve.

**Comment by bithabib** [comment]
Hi @Yenthe666,

I wanted to let you know that I've addressed the issue you raised about running the script on Odoo 17.0 with Ubuntu 22.04. I've tested and resolved the errors you mentioned, and I also handled the additional steps required for installing dependencies. The script should now work smoothly.

I've submitted a PR (#424) to the repository with these fixes: "Install 17.0 on Ubuntu 22.04LTS Bug fixing"

Thanks for bringing this up!

Best regards,
Bithabib

**Comment by Yenthe666** [comment]
> Hi @Yenthe666,
> 
> I wanted to let you know that I've addressed the issue you raised about running the script on Odoo 17.0 with Ubuntu 22.04. I've tested and resolved the errors you mentioned, and I also handled the additional steps required for installing dependencies. The script should now work smoothly.
> 
> I've submitted a PR (#424) to the repository with these fixes: "Install 17.0 on Ubuntu 22.04LTS Bug fixing"
> 
> Thanks for bringing this up!
> 
> Best regards, Bithabib


Ehm, you simply removed two add-apts? :) Does that really solve it?

**Comment by bithabib** [comment]
Yes I have checked with digital ocean, aws and google cloud
