### ISSUE TITLE
Error install "pysftp" install ubuntu 14.04 odoo 10

### ISSUE THREAD

**Issue by jjmc1987** [Yenthe666/InstallScript#44]
Hi friends, I have problemas tu install pysftp, the log to pip is:

byte-compiling /usr/local/lib/python2.7/dist-packages/cryptography/x509/oid.py to oid.pyc
    byte-compiling /usr/local/lib/python2.7/dist-packages/cryptography/x509/general_name.py to general_name.pyc
    byte-compiling /usr/local/lib/python2.7/dist-packages/cryptography/x509/name.py to name.pyc
    running install_egg_info
    Copying src/cryptography.egg-info to /usr/local/lib/python2.7/dist-packages/cryptography-1.8.1.egg-info
    running install_scripts
    writing list of installed files to '/tmp/pip-ZGKkqj-record/install-record.txt'
  Found existing installation: setuptools 3.3
    Not uninstalling setuptools at /usr/lib/python2.7/dist-packages, owned by OS
  Running setup.py install for cffi
    Running command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__)$
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 12, in <module>
        import setuptools.version
      File "/usr/local/lib/python2.7/dist-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 72, in <module>
        import packaging.requirements
      File "/usr/local/lib/python2.7/dist-packages/packaging/requirements.py", line 59, in <module>
        MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
    TypeError: __call__() takes exactly 2 arguments (1 given)
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/cffi/setup.py';exec(compile(getattr(tokenize, 'open', op$
    Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 12, in <module>

    import setuptools.version

  File "/usr/local/lib/python2.7/dist-packages/setuptools/version.py", line 1, in <module>

    import pkg_resources

  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 72, in <module>

    import packaging.requirements

    import packaging.requirements

  File "/usr/local/lib/python2.7/dist-packages/packaging/requirements.py", line 59, in <module>

    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")

TypeError: __call__() takes exactly 2 arguments (1 given)

**Comment by Yenthe666** [comment]
Hi @jjmc1987,

Thank you for your report. There is no pysftp in my install script though. I assume this was from my auto backup tool.
In case you still face this then please update your pip installation, update your Ubuntu and try again.

Regards,
Yenthe
