### ISSUE TITLE
Odoo Server Error

### ISSUE THREAD

**Issue by DhirajPalekar** [Yenthe666/InstallScript#57]
Installation worked fine but now receive 'Odoo server Error' every time I log into odoo

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/fields.py", line 911, in __get__
    value = record.env.cache.get(record, self)
  File "/odoo/odoo-server/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7f227a235390>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 86, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/calendar/controllers/main.py", line 68, in notify
    return request.env['calendar.alarm_manager'].get_next_notif()
  File "/odoo/odoo-server/addons/calendar/models/calendar.py", line 401, in get_next_notif
    all_notif.append(self.do_notif_reminder(alert))
  File "/odoo/odoo-server/addons/calendar/models/calendar.py", line 428, in do_notif_reminder
    message = meeting.display_time
  File "/odoo/odoo-server/odoo/fields.py", line 915, in __get__
    self.determine_value(record)
  File "/odoo/odoo-server/odoo/fields.py", line 1026, in determine_value
    self.compute_value(recs)
  File "/odoo/odoo-server/odoo/fields.py", line 982, in compute_value
    self._compute_value(records)
  File "/odoo/odoo-server/odoo/fields.py", line 973, in _compute_value
    getattr(records, self.compute)()
  File "/odoo/odoo-server/addons/calendar/models/calendar.py", line 821, in _compute_display_time
    meeting.display_time = self._get_display_time(meeting.start, meeting.stop, meeting.duration, meeting.allday)
  File "/odoo/odoo-server/addons/calendar/models/calendar.py", line 686, in _get_display_time
    date_str = date.strftime(format_date).decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'

**Comment by Yenthe666** [comment]
Hi @DhirajPalekar,

This bug is Odoo related, not to the install script. It is coming from the encoding in the calendar - you can create a bug report at github.com/odoo/odoo for that 😉 

Regards,
Yenthe

**Comment by DhirajPalekar** [comment]
Thank for the response, Yenthe! And for the script as well it worked just perfect. Will post the bug report on odoo. 
Regards,
Dhiraj

**Comment by Yenthe666** [comment]
You're welcome! First try to update your Odoo by the way. There have been quite a few fixes in the last week. 👍

**Comment by DhirajPalekar** [comment]
Definitely will give it a try. Thanks! :)

**Comment by chris001** [comment]
@Yenthe666 About updating your Odoo.... should the script be able to install the newest nightly, and from then on, cleanly "upgrade-install" the newest nightly over the current one, without messing up the config files, etc.?

**Comment by Yenthe666** [comment]
Hi @chris001,

The nightly (deb packages) haven't been on my priority really. I always used Github and never imagined that the installation script would become so much used and wanted. 😄 
I believe it is quite some work so I'd like to keep that wishlist for now - maybe if I find quite some spare time that I'll add this in though.

**Comment by chris001** [comment]
@Yenthe666 
Maybe installing the nightly `source` directory could be almost identical to the process of installing from github source.

**Comment by Yenthe666** [comment]
I'd have to check, who uses `source` directories though? Are they so commonly used?

**Comment by chris001** [comment]
@Yenthe666 
The `source` directory SHOULD be exactly the same as the github source, on that night.
BUT, it might be different, when an error is made in the process.
SO, supporting install from `source` directory would be a nice way to test, is the GITHUB source code the SAME or DIFFERENT from the current NIGHTLY source code.
When there is a difference, this difference would be nice to detect, so that bugs could be explained by a difference in the source code.
More info here:
https://www.packtpub.com/mapt/book/big_data_and_business_intelligence/9781784392796/1/ch01lvl1sec09/installing-odoo-from-source
