### ISSUE TITLE
I have this problem when i install odoo 11 community with the script 

### ISSUE THREAD

**Issue by NadirBey** [Yenthe666/InstallScript#66]
![odoo 11 probleme](https://user-images.githubusercontent.com/26307163/32121876-b17ea2de-bb5e-11e7-8774-a0f7a98eac5b.PNG)

**Comment by Yenthe666** [comment]
Hi @NadirBey,

Thanks for the report. What OS and which version of the script? When did you last try this?

**Comment by NadirBey** [comment]
Hi ,

I have a virtual machine Ubuntu server 16.04 and the version of the sricpt is this : 
wget https://raw.githubusercontent.com/Yenthe666/InstallScript/11.0/odoo_install.sh

I retrieve it from a site , not ghitub .

A user give me this answer, what about you.
Dependencies
sudo apt-get install -y npm

sudo ln -s /usr/bin/nodejs /usr/bin/node

sudo npm install -g less less-plugin-clean-css

sudo apt-get install -y node-less

**Comment by NadirBey** [comment]
Have you got the last version of all the version 8.9.10.11 ?

**Comment by Yenthe666** [comment]
Not sure what you're trying to say..
This script downloads the latest Odoo version from github.com/odoo/odoo and installs all dependencies that you need.

**Comment by chris001** [comment]
@NadirBey 
You should try it again, but use the exact official installation steps listed here:
https://github.com/Yenthe666/InstallScript

**Comment by hanguyen92205** [comment]
i installed Odoo 11.0 comunity with Ubuntu serve 16.04LTS, It is the same isues .
After that, i retry install but odoo can not work
![image](https://user-images.githubusercontent.com/13514363/32369123-a3a39154-c0ba-11e7-8e25-b99c56fb5e45.png)

![image](https://user-images.githubusercontent.com/13514363/32369081-7d7d1b76-c0ba-11e7-9f37-afe3b9290128.png)

**Comment by Yenthe666** [comment]
@hanguyen92205,

By looking at your screenshots I can see you already had an Odoo with the exact same settings (as you can see from the error `The user 'odoo' is already a member of sudo` for example).
When you run the install script twice for the same thing your installation will absolutely fail. Check your Odoo configuration file - it will have double parameters which prevents Odoo from working. Also have a look at your logfile (/var/log/odoo)

**Comment by hanguyen92205** [comment]
so, how to do uninstall odoo?
Can you help me, please

**Comment by Yenthe666** [comment]
@hanguyen92205 remove the user, the configuration file, the logfile and Odoo. Then you can do a clean install.
Something along the lines of:
`sudo rm -R /var/log/odoo`
`sudo rm /etc/odoo-server.conf` (don't forget to also remove the service)
`sudo rm -R /odoo`
`sudo deluser odoo`

**Comment by hanguyen92205** [comment]
Thank @Yenthe666 
I has to reinstall odoo. It's OK

**Comment by hanguyen92205** [comment]
I install app Live chat , But it's not work
This is logfile : 
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/odoo/odoo-server/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7f252a5210d0>, 'base.user_demo')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 639, in _tag_record
    f_val = self.id_get(f_ref)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 724, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 730, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_model.py", line 1314, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup
  File "/odoo/odoo-server/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_model.py", line 1303, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: base.user_demo

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 924, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 912, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-39>", line 2, in button_immediate_install
  File "/odoo/odoo-server/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/module/module.py", line 438, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo/odoo-server/odoo/addons/base/module/module.py", line 531, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo/odoo-server/odoo/modules/registry.py", line 84, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 159, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/odoo/odoo-server/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 738, in parse
    self.parse(rec, mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 639, in _tag_record
    f_val = self.id_get(f_ref)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 724, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 730, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_model.py", line 1314, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup
  File "/odoo/odoo-server/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_model.py", line 1303, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
odoo.tools.convert.ParseError: "External ID not found in the system: base.user_demo" while parsing /odoo/odoo-server/addons/calendar/data/calendar_demo.xml:31, near
<record id="calendar_event_2" model="calendar.event">
            <field name="active" eval="True"/>
            <field name="user_id" ref="base.user_demo"/>
            <field name="partner_ids" eval="[(6,0,[ref('base.partner_root'),ref('base.res_partner_4'),ref('base.res_partner_3')])]"/>
            <field name="name">Initial discussion</field>
            <field name="description">Discussion with partner for product.</field>
            <field name="categ_ids" eval="[(6,0,[ref('categ_meet3')])]"/>
            <field name="start" eval="time.strftime('%Y-%m-05 12:00:00')"/>
            <field name="stop" eval="time.strftime('%Y-%m-05 19:00:00')"/>
            <field name="allday" eval="False"/>
            <field name="duration" eval="7.0"/>
            <field name="state">draft</field>
        </record>

**Comment by chris001** [comment]
@hanguyen92205 
https://www.odoo.com/forum/help-1/question/server-error-when-installing-modules-in-odoo-10-enterprise-117447

**Comment by Yenthe666** [comment]
Oh boy - never delete users. 😉

**Comment by hanguyen92205** [comment]
thank bro
👍 👍 👍

**Comment by NadirBey** [comment]
Hi Yen ,

I have a question ... Your script for Odoo V8 is it still functional ?

Can i have the path.



*Nadir Bey *

* Erp Functional Consultant  / Business Management*

*mobile : +213 (0) 698145494 / +213 (0) 560250996*

*email : beynadir1982@gmail.com <beynadir1982@gmail.com>*



Please note that Algerian Week End is Friday and Saturday.
Ce message et toutes les pièces jointes (ci-après le "message") sont
confidentiels et susceptibles de contenir des informations couvertes par le
secret professionnel. Ce message est établi a l'intention exclusive de ses
destinataires. Toute utilisation ou diffusion non autorisée est interdite.
Tout message électronique est susceptible d'altération. Nadir BEY décline
toute responsabilité au titre de ce message s'il a été altéré, déformé ou
falsifié. ========================================================= This
message and any attachments (the "message") are confidential, intended
solely for the addressees, and may contain legally privileged information.
Any unauthorised use or dissemination is prohibited. E-mails are
susceptible to alteration. Nadir BEY never shall be liable for the message
if altered, changed or falsified.



2017-10-29 13:26 GMT+01:00 Yenthe V.G <notifications@github.com>:

**Comment by Yenthe666** [comment]
@NadirBey yes it is - see https://github.com/Yenthe666/InstallScript/blob/8.0/odoo_install.sh

**Comment by NadirBey** [comment]
I don't find it

*Nadir Bey *

* Erp Functional Consultant  / Business Management*

*mobile : +213 (0) 698145494 / +213 (0) 560250996*

*email : beynadir1982@gmail.com <beynadir1982@gmail.com>*



Please note that Algerian Week End is Friday and Saturday.
Ce message et toutes les pièces jointes (ci-après le "message") sont
confidentiels et susceptibles de contenir des informations couvertes par le
secret professionnel. Ce message est établi a l'intention exclusive de ses
destinataires. Toute utilisation ou diffusion non autorisée est interdite.
Tout message électronique est susceptible d'altération. Nadir BEY décline
toute responsabilité au titre de ce message s'il a été altéré, déformé ou
falsifié. ========================================================= This
message and any attachments (the "message") are confidential, intended
solely for the addressees, and may contain legally privileged information.
Any unauthorised use or dissemination is prohibited. E-mails are
susceptible to alteration. Nadir BEY never shall be liable for the message
if altered, changed or falsified.



2018-03-16 20:34 GMT+01:00 Yenthe V.G <notifications@github.com>:
