### ISSUE TITLE
Studio missing dependencies 

### ISSUE THREAD

**Issue by crazydanilo** [Yenthe666/InstallScript#68]
Hello,

I am using the latest version for Enterprise Edition for v11, but it seems that some dependencies are missing for the STUDIO module. I have the following error whenever I want to add a column to any List View:

Odoo Server Error - Validation Error
Invalid view definition

from console:

2017-10-31 22:04:12,297 13636 ERROR test odoo.tools.view_validation: <string>:3:0:ERROR:RELAXNGV:RELAXNG_ERR_NOELEM: Expecting an element data, got nothing
2017-10-31 22:04:12,298 13636 ERROR test odoo.tools.view_validation: <string>:3:0:ERROR:RELAXNGV:RELAXNG_ERR_INVALIDATTR: Invalid attribute studio_groups for element field
2017-10-31 22:04:12,298 13636 ERROR test odoo.tools.view_validation: <string>:2:0:ERROR:RELAXNGV:RELAXNG_ERR_EXTRACONTENT: Element tree has extra content: field
2017-10-31 22:04:12,298 13636 ERROR test odoo.tools.view_validation: Invalid XML:  Get RNG validator and validate RNG file.

FYI, if testing in runbot.odoo.com its working.

**Comment by chris001** [comment]
What errors show on the console when you do:
```
    sudo service odoo-server stop
    cd /odoo/odoo-server
    sudo su odoo
    ./odoo-bin -c /etc/odoo-server.conf
```

**Comment by crazydanilo** [comment]
odoo@ip-172-31-18-89:~/odoo-server$ ./odoo-bin -c /etc/odoo-server.conf
Exception in thread odoo.service.httpd:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/odoo/odoo-server/odoo/service/server.py", line 255, in http_thread
    self.httpd = ThreadedWSGIServerReloadable(self.interface, self.port, app)
  File "/odoo/odoo-server/odoo/service/server.py", line 106, in __init__
    handler=RequestHandler)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 504, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/odoo/odoo-server/odoo/service/server.py", line 116, in server_bind
    super(ThreadedWSGIServerReloadable, self).server_bind()
  File "/usr/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

**Comment by crazydanilo** [comment]
odoo@ip-172-31-18-89:~/odoo-server$ ./odoo-bin -c /etc/odoo-server.conf
Exception in thread odoo.service.httpd:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/odoo/odoo-server/odoo/service/server.py", line 255, in http_thread
    self.httpd = ThreadedWSGIServerReloadable(self.interface, self.port, app)
  File "/odoo/odoo-server/odoo/service/server.py", line 106, in __init__
    handler=RequestHandler)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 504, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/odoo/odoo-server/odoo/service/server.py", line 116, in server_bind
    super(ThreadedWSGIServerReloadable, self).server_bind()
  File "/usr/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

**Comment by chris001** [comment]
That just means that the `odoo-server` service is already running and using the port so it can't start up another one.  You have to be sure the service is stopped before you can run it from the command line like that.

**Comment by Yenthe666** [comment]
Yep, exactly.
Do a service odoo-server stop before running your Odoo from the terminal.

**Comment by crazydanilo** [comment]
Hi, 

Well I am not sure which one was missing, or if some version of the dependencies was no correct, but once I run:

https://github.com/odoo/odoo/blob/11.0/requirements.txt

It fixed the issue.

**Comment by chris001** [comment]
@Yenthe666 
Maybe a good idea to modify script so that after it clones odoo 11 repo it installs from the file `pip3 install -r requirements.txt` taken directly from official odoo 11 repo so it's always up to date and accurate.
