### ISSUE TITLE
[11] Lots of isues in three odoo 11 instalations in production using this installscript

### ISSUE THREAD

**Issue by fgarcia-humanoide** [Yenthe666/InstallScript#76]
The mail does not work

Problems with permissions

Does not work with firefox , and works ok with chrome.

The advice will be to wait two years until odoo 11 gets mature.

**Comment by fgarcia-humanoide** [comment]
Sorry , it works on firefox, the problem was solved clearing the cache.

**Comment by Yenthe666** [comment]
So what are the issues with the mailserver and the permissions? Can you please give more info/context?
P.s: the mailserver issue has to be an Odoo issue in general then.

**Comment by chris001** [comment]
@fgarcia-humanoide 
Please share screen capture video recording in your broswer
https://www.apowersoft.com/free-online-screen-recorder

**Comment by chris001** [comment]
@fgarcia-humanoide 
You can download and run again, the newest version fixes errors caused by missing libraries (`num2words` and others).
```
cd ~
wget https://github.com/chris001/InstallScript/blob/patch-2/odoo_install.sh
chmod +x odoo_install.sh
./odoo_install.sh
```

**Comment by fgarcia-humanoide** [comment]
Lots of problems when using

python3 /opt/odoo/odoo-server/odoo-bin -c /etc/odoo-server.conf --update=all -d databasename

after updating odoo 11

root@madamaodoo:/var/log/odoo# tail -50 odoo-server.log
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 766, in get_code
  File "<frozen importlib._bootstrap_external>", line 818, in get_data
PermissionError: [Errno 13] Permission denied: '/root/.reportlab_mods'
2017-11-27 19:27:46,132 6141 CRITICAL enchufesolar odoo.service.server: Failed to initialize database `dabatasename`.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/reportlab/__init__.py", line 50, in <module>
    import reportlab_mods   #application specific modifications can be anywhere on python path
ImportError: No module named 'reportlab_mods'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/service/server.py", line 925, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/opt/odoo/odoo-server/odoo/modules/registry.py", line 84, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo-server/odoo/modules/loading.py", line 284, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report)
  File "/opt/odoo/odoo-server/odoo/modules/loading.py", line 121, in load_module_graph
    load_openerp_module(package.name)
  File "/opt/odoo/odoo-server/odoo/modules/module.py", line 368, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/opt/odoo/odoo-server/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 4, in <module>
  File "/opt/odoo/odoo-server/odoo/addons/base/ir/__init__.py", line 9, in <module>
    from . import ir_actions_report
  File "/opt/odoo/odoo-server/odoo/addons/base/ir/ir_actions_report.py", line 24, in <module>
    from reportlab.graphics.barcode import createBarcodeDrawing
  File "/usr/local/lib/python3.5/dist-packages/reportlab/__init__.py", line 53, in <module>
    _fake_import(os.path.expanduser(os.path.join('~','.reportlab_mods')),'reportlab_mods')
  File "/usr/local/lib/python3.5/dist-packages/reportlab/__init__.py", line 27, in _fake_import
    sys.modules[name] = m.load_module(name)
  File "<frozen importlib._bootstrap_external>", line 388, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 809, in load_module
  File "<frozen importlib._bootstrap_external>", line 668, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 766, in get_code
  File "<frozen importlib._bootstrap_external>", line 818, in get_data
PermissionError: [Errno 13] Permission denied: '/root/.reportlab_mods'

**Comment by chris001** [comment]
@fgarcia-humanoide 
1. Did you run that update database command `python3 /opt/odoo/odoo-server/odoo-bin -c /etc/odoo-server.conf --update=all -d databasename` as user `root` or as user `odoo`?
2. What's the output of `groups odoo`?
3. Run the command as user `odoo` and report back your results here:
```
sudo su - odoo
python3 /opt/odoo/odoo-server/odoo-bin -c /etc/odoo-server.conf --update=all -d databasename
exit
```

**Comment by fgarcia-humanoide** [comment]
I did it with user odoo

the output is 
odoo : odoo sudo

**Comment by chris001** [comment]
Did you run that command with `sudo` in front? It looks like it ran with `sudo` in front, because it was trying to look in `/root/.reportlab_mods`.  It needs to run without `sudo`, as user `odoo`.

**Comment by fgarcia-humanoide** [comment]
The script creates user odoo in the sudoers group.

Now user odoo is not in the sudoers group. There are no errors with updata all

thanks

**Comment by chris001** [comment]
OK @fgarcia-humanoide , since there are no errors with command `python3 /opt/odoo/odoo-server/odoo-bin -c /etc/odoo-server.conf --update=all -d databasename`, is your issue resolved now.

**Comment by chris001** [comment]
@fgarcia-humanoide 
Fixed 2 bugs, just now, related to installing Enterprise.
If you are using Enterprise, could you try running this installer again.
```
cd ~
wget https://github.com/chris001/InstallScript/blob/patch-2/odoo_install.sh
chmod +x odoo_install.sh
./odoo_install.sh --enterprise
```

**Comment by fgarcia-humanoide** [comment]
Hi Chris,

Thanks for your help.

I am using community edition.
The issue was resolved being odoo out of the sudoers group.

Still probmems with mail, and impossible to sinc to google calendar. Things that can be caused by other reasons and not for the script.

**Comment by chris001** [comment]
@fgarcia-humanoide 
Excellent.
Here's some references to help you with mail problems.
Try these and report back your results!
1. https://www.odoo.com/documentation/user/11.0/discuss/email_servers.html
2. https://www.odoo.com/forum/help-1/question/configure-incoming-email-in-odoo-10-111159
3. https://www.odoo.com/forum/help-1/question/how-to-setup-email-alias-111570
4. http://www.technaureus.com/configure-incoming-and-outgoing-mail-server-in-odoo/
5. https://www.odoo.yenthevg.com/configure-outgoing-mailservers/

Is this your G calendar issue ?
https://github.com/odoo/odoo/issues/19955

**Comment by adamckie** [comment]
I have installed Odoo 11 based on the given script. Odoo service is running and i am just using my IP xx.xx.xx.xx:8069 I dont get any results. ERR_CONNECTION_REFUSED. Can someone help?

**Comment by Yenthe666** [comment]
@adamckie please check the Odoo log.
